In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3825, 7388, 2224, 1406],
 [3825, 7388, 2224, 2492],
 [3825, 6800, 2224, 2720],
 [2679, 4493, 6670, 9280, 7378],
 [2679, 4493, 6670, 9280, 9252],
 [7725, 3825, 8852, 2224, 8330],
 [3714, 7279, 7352, 9280]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3825 7388 2224 1406]
 [   0    0    0    0 3825 7388 2224 2492]
 [   0    0    0    0 3825 6800 2224 2720]
 [   0    0    0 2679 4493 6670 9280 7378]
 [   0    0    0 2679 4493 6670 9280 9252]
 [   0    0    0 7725 3825 8852 2224 8330]
 [   0    0    0    0 3714 7279 7352 9280]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 253ms/step


array([[[ 0.04797282,  0.01646096,  0.00498118,  0.01234262,
         -0.04706139,  0.04165937, -0.04993344,  0.00427185,
          0.02270651,  0.02036922],
        [ 0.04797282,  0.01646096,  0.00498118,  0.01234262,
         -0.04706139,  0.04165937, -0.04993344,  0.00427185,
          0.02270651,  0.02036922],
        [ 0.04797282,  0.01646096,  0.00498118,  0.01234262,
         -0.04706139,  0.04165937, -0.04993344,  0.00427185,
          0.02270651,  0.02036922],
        [ 0.04797282,  0.01646096,  0.00498118,  0.01234262,
         -0.04706139,  0.04165937, -0.04993344,  0.00427185,
          0.02270651,  0.02036922],
        [ 0.03969716, -0.02386143,  0.02448306, -0.00039028,
          0.00164249,  0.00838881,  0.04314828,  0.02238056,
         -0.03649067, -0.04830509],
        [-0.00498309,  0.0354285 , -0.00740591,  0.03880927,
         -0.03943761, -0.01995977,  0.01850096, -0.04998455,
         -0.0453051 , -0.00251347],
        [ 0.0372096 , -0.02716875,  0.00775344, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3825, 7388, 2224, 1406])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 30ms/step


array([[ 0.04797282,  0.01646096,  0.00498118,  0.01234262, -0.04706139,
         0.04165937, -0.04993344,  0.00427185,  0.02270651,  0.02036922],
       [ 0.04797282,  0.01646096,  0.00498118,  0.01234262, -0.04706139,
         0.04165937, -0.04993344,  0.00427185,  0.02270651,  0.02036922],
       [ 0.04797282,  0.01646096,  0.00498118,  0.01234262, -0.04706139,
         0.04165937, -0.04993344,  0.00427185,  0.02270651,  0.02036922],
       [ 0.04797282,  0.01646096,  0.00498118,  0.01234262, -0.04706139,
         0.04165937, -0.04993344,  0.00427185,  0.02270651,  0.02036922],
       [ 0.03969716, -0.02386143,  0.02448306, -0.00039028,  0.00164249,
         0.00838881,  0.04314828,  0.02238056, -0.03649067, -0.04830509],
       [-0.00498309,  0.0354285 , -0.00740591,  0.03880927, -0.03943761,
        -0.01995977,  0.01850096, -0.04998455, -0.0453051 , -0.00251347],
       [ 0.0372096 , -0.02716875,  0.00775344, -0.02502441, -0.04199778,
        -0.00062567, -0.04708881,  0.04150566